{{- range $i, $connector := .Values.kafkaConnect.connectors }}
{{- $name := printf "%s-%s-%s-%d" (include "kafkaConnect.name" $) $connector.name $connector.type $i | trunc 63 }}
apiVersion: v1
kind: Secret
type: "Opaque"
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    {{- include "kafkaConnect.labels" $ | nindent 4 }}
data:
  snowflake.json: {{ $.Files.Get $connector.snowflake.configPath | b64enc }}
  connect-distributed.properties: {{ $.Files.Get $connector.connectDistributed.configPath | b64enc }}
---
{{- end }}
