{{- range $i, $connector := .Values.kafkaConnect.connectors }}
{{- $name := printf "%s-%s-%s-%d" (include "kafkaConnect.name" $) $connector.name $connector.type $i | trunc 63 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    name: {{ $name }}
    {{- include "kafkaConnect.selectorLabels" $ | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8083
---
{{- end }}
