{{- if .Values.demoApp.enabled }}
{{- with .Values.demoApp }}
apiVersion: v1
kind: Secret
type: "Opaque"
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    {{- include "kafkaConnect.labels" $ | nindent 4 }}
data:
  config.yaml: {{ $.Files.Get .configPath | b64enc }}
{{- end }}
{{- end }}
